api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    collection:
        pagination:
            client_enabled: true
            client_items_per_page: true
            items_per_page: 10 # Default value
            items_per_page_parameter_name: length # Default value
