doctrine:
    dbal:
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
        types:
            uuid: Ramsey\Uuid\Doctrine\UuidType
        default_connection: default
        connections:
            default:
                # configure these for your database server
                url: '%env(resolve:DATABASE_URL_DEFAULT)%'
                charset: utf8mb4
            simsdm:
                # configure these for your database server
                url: '%env(resolve:DATABASE_URL_SIMSDM)%'
                charset: utf8mb4    
    orm:
        auto_generate_proxy_classes: false
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    Frrbac:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Frrbac'
                        prefix: 'App\Entity\Frrbac'
                        alias: Frrbac
            simsdm:
                connection: simsdm
                mappings:
                    Simsdm:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Simsdm'
                        prefix: 'App\Entity\Simsdm'
                        alias: Simsdm            
